SystemOrganization addCategory: #MUDClient!
SystemOrganization addCategory: 'MUDClient-Model'!
SystemOrganization addCategory: 'MUDClient-Model-Plugin'!
SystemOrganization addCategory: 'MUDClient-Model-Telnet'!
SystemOrganization addCategory: 'MUDClient-View'!
SystemOrganization addCategory: 'MUDClient-View-Glamour'!
SystemOrganization addCategory: 'MUDClient-View-Magritte'!
SystemOrganization addCategory: 'MUDClient-View-Morph'!
