as yet unclassified
planetsForTest
	^ 'Coruscant       Corusca Sector        Rebel Alliance            99.0
Corellia        Corellian System      Rebel Alliance            89.0
Dac             Calamari System       Rebel Alliance            100.0
Lorrd           Kanz System           Rebel Alliance            100.0
Ryloth          Gaulus Sector         Rebel Alliance            100.0
Tatooine        Arkanis Sector        Rebel Alliance            100.0
Bespin          Anoat Sector          Neutral Government        100.0
Nal Hutta       Y''toub System         Rebel Alliance            100.0
Kashyyyk        Mytaranor Sector      Rebel Alliance            100.0
Alderaan        Alderaan System       Rebel Alliance            100.0
Korriban        Horuset                                         2.0
Mandalore       Mandalore Sector      Neutral Government        100.0
Ithor           Ottega System         Rebel Alliance            100.0
Hoth-VI         Hoth System           Rebel Alliance            100.0'