as yet unclassified
systemsForTest
	^ 'Corusca Sector           ( 0, 0 )
Corellian System         ( 15, -17 )
Calamari System          ( 24, 5 )
Kanz System              ( 16, 23 )
Gaulus Sector            ( 90, -73 )
Arkanis Sector           ( 69, -92 )
Anoat Sector             ( 90, -40 )
Y''toub System            ( 77, -65 )
Mytaranor Sector         ( 48, -48 )
Alderaan System          ( 40, -30 )
Horuset                  ( 103, 5 )
Mandalore Sector         ( 116, -43 )
Ottega System            ( 19, -58 )
Hoth System              ( 100, -110 )'