as yet unclassified
planetsForTest
	^ 'Coruscant       Corusca Sector        The Galactic Empire       100.0
Corellia        Corellian System      The Galactic Empire       100.0
Dac             Calamari System       The Galactic Empire       100.0
Lorrd           Kanz System           The Galactic Empire       100.0
Ryloth          Gaulus Sector         The Galactic Empire       100.0
Tatooine        Arkanis Sector        The Galactic Empire       100.0
Bespin          Anoat Sector          The Galactic Empire       100.0
Nal Hutta       Y''toub System         The Galactic Empire       100.0
Kashyyyk        Mytaranor Sector      Neutral Government        100.0
Alderaan        Alderaan System       The Galactic Empire       100.0
Korriban        Horuset               Neutral Government        100.0
Ithor           Ottega System         Neutral Government        100.0'