SystemOrganization addCategory: #'Rpg-Telnet-Client'!
SystemOrganization addCategory: 'Rpg-Telnet-Client-Editor'!
SystemOrganization addCategory: 'Rpg-Telnet-Client-Editor-Generator'!
SystemOrganization addCategory: 'Rpg-Telnet-Client-Editor-Morph'!
SystemOrganization addCategory: 'Rpg-Telnet-Client-Editor-Theme'!
SystemOrganization addCategory: 'Rpg-Telnet-Client-Model'!
SystemOrganization addCategory: 'Rpg-Telnet-Client-Model-Telnet'!
