SystemOrganization addCategory: #'RpgClient-Telnet'!
SystemOrganization addCategory: 'RpgClient-Telnet-Editor'!
SystemOrganization addCategory: 'RpgClient-Telnet-Editor-Generator'!
SystemOrganization addCategory: 'RpgClient-Telnet-Editor-Morph'!
SystemOrganization addCategory: 'RpgClient-Telnet-Editor-Theme'!
SystemOrganization addCategory: 'RpgClient-Telnet-Model'!
SystemOrganization addCategory: 'RpgClient-Telnet-Model-Telnet'!
